name: chemspace
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - openbabel
  - rdkit
  - requests
  - numpy
  - pandas
  - pytest
  - ipykernel
  - datasets
  - transformers
<<<<<<< HEAD
  - pytorch
=======
  
>>>>>>> ad9c930 (updated requirements: inlcuded transformers)
