name: chemspace
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - openbabel
  - rdkit
  - requests
  - numpy
  - pandas
  - pytest
  - ipykernel
  - datasets
<<<<<<< HEAD
  - transformers
  
=======
  - seaborn
  - pytorch
>>>>>>> 0f74da9 (First implementation of the projectors)
