name: Unit tests

on: 
  push:
    branches: ['main'] # Run when anyting is pushed to main
  pull_request:
    branches: ['*'] # Run when there's a pull reqeust from any branch
  workflow_dispatch: # Allow for manual triggering of this workflow
concurrency:
  # cancel in progress workflow run when another from the same group (branch and PR) is triggered
  # {{ github.workflow }}: the workflow name is used to generate the concurrency group. This allows you to have more than one workflows
  # {{ github.ref_type }}: the type of Git ref object created in the repository. Can be either branch or tag
  # {{ github.event.pull_request.number}}: get PR number
  # {{ github.sha }}: full commit sha
  # credit: https://github.com/Sage-Bionetworks-Workflows/sagetasks/blob/main/.github/workflows/ci.yml
  group: >-
    ${{ github.workflow }}-${{ github.ref_type }}-
    ${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    #----------------------------------------------
    #       check-out repo and set-up python
    #----------------------------------------------
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
        
    #----------------------------------------------
    #       add anaconda to path
    #----------------------------------------------    
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
        
    #----------------------------------------------
    #      Install environment packages
    #----------------------------------------------
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
        
    #----------------------------------------------
    #      Lint - currently disabled, will decide if we want
    #----------------------------------------------
    #- name: Lint with flake8
    #  run: |
    #    conda install flake8
    #    # stop the build if there are Python syntax errors or undefined names
    #    flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #    # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #    flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    #----------------------------------------------
    #       Run unit tests - disabled until we add tests
    #----------------------------------------------
    - name: Test with pytest
      run: |
        conda install pytest
        pytest -m "not zipped_files"
